# Generated by Django 4.2.7 on 2025-11-14 18:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chatbots", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatbot",
            name="crm_enabled",
            field=models.BooleanField(default=False, help_text="Enable CRM integration for this chatbot"),
        ),
        migrations.AddField(
            model_name="chatbot",
            name="crm_provider",
            field=models.CharField(
                choices=[("hubspot", "HubSpot"), ("zoho", "Zoho CRM"), ("salesforce", "Salesforce")],
                default="hubspot",
                help_text="CRM provider type",
                max_length=50,
            ),
        ),
    ]
