# Generated by Django 4.2.7 on 2025-11-30 14:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_organization_teammember_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="message_quota",
        ),
        migrations.RemoveField(
            model_name="user",
            name="messages_used",
        ),
        migrations.RemoveField(
            model_name="user",
            name="quota_reset_date",
        ),
        migrations.AddField(
            model_name="user",
            name="credits_reset_date",
            field=models.DateTimeField(default=django.utils.timezone.now, help_text="When credits reset"),
        ),
        migrations.AddField(
            model_name="user",
            name="credits_used",
            field=models.PositiveIntegerField(default=0, help_text="Credits used this period"),
        ),
        migrations.AddField(
            model_name="user",
            name="max_ai_actions",
            field=models.PositiveIntegerField(default=0, help_text="AI Actions per agent"),
        ),
        migrations.AddField(
            model_name="user",
            name="max_ai_agents",
            field=models.PositiveIntegerField(default=1, help_text="Maximum AI agents allowed"),
        ),
        migrations.AddField(
            model_name="user",
            name="max_seats",
            field=models.PositiveIntegerField(default=1, help_text="Team seats allowed"),
        ),
        migrations.AddField(
            model_name="user",
            name="message_credits",
            field=models.PositiveIntegerField(default=50, help_text="Monthly message credits (Chatbase style)"),
        ),
        migrations.AddField(
            model_name="user",
            name="storage_limit_mb",
            field=models.PositiveIntegerField(default=1, help_text="Storage limit per AI agent in MB"),
        ),
    ]
