# Generated by Django 4.2.7 on 2025-11-30 14:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("billing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="max_chatbots",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="max_file_size_mb",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="max_knowledge_sources",
        ),
        migrations.RemoveField(
            model_name="subscriptionplan",
            name="message_quota",
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="agents_persist",
            field=models.BooleanField(default=True, help_text="Agents persist (false = deleted after inactivity)"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_advanced_analytics",
            field=models.BooleanField(default=False, help_text="Advanced analytics included"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_api_access",
            field=models.BooleanField(default=False, help_text="API access included"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_custom_branding",
            field=models.BooleanField(default=False, help_text="Custom branding options"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_integrations",
            field=models.BooleanField(default=False, help_text="Basic integrations included"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="has_priority_support",
            field=models.BooleanField(default=False, help_text="Priority support included"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="inactivity_deletion_days",
            field=models.PositiveIntegerField(default=0, help_text="Days before deletion (0 = never delete)"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_ai_actions",
            field=models.PositiveIntegerField(default=0, help_text="Maximum AI Actions per agent"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_ai_agents",
            field=models.PositiveIntegerField(default=1, help_text="Maximum number of AI agents (chatbots)"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_seats",
            field=models.PositiveIntegerField(default=1, help_text="Maximum number of team seats"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="max_training_links",
            field=models.PositiveIntegerField(default=10, help_text="Maximum training links (0 = unlimited)"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="message_credits",
            field=models.PositiveIntegerField(default=50, help_text="Monthly message credits (Chatbase style)"),
        ),
        migrations.AddField(
            model_name="subscriptionplan",
            name="storage_limit_mb",
            field=models.PositiveIntegerField(default=1, help_text="Storage limit per AI agent in MB"),
        ),
        migrations.AddField(
            model_name="usagerecord",
            name="ai_actions_used",
            field=models.PositiveIntegerField(default=0, help_text="AI Actions executed"),
        ),
        migrations.AddField(
            model_name="usagerecord",
            name="message_credits_used",
            field=models.PositiveIntegerField(default=0, help_text="Message credits consumed"),
        ),
        migrations.CreateModel(
            name="PlanAddon",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                ("deleted_at", models.DateTimeField(blank=True, db_index=True, null=True)),
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True)),
                ("price_monthly", models.DecimalField(decimal_places=2, help_text="Monthly price in USD", max_digits=10)),
                (
                    "addon_type",
                    models.CharField(
                        choices=[
                            ("credits", "Extra Message Credits"),
                            ("agents", "Additional AI Agents"),
                            ("storage", "Extra Storage"),
                            ("branding", "Custom Branding"),
                            ("domain", "Custom Domain"),
                            ("support", "Priority Support"),
                        ],
                        max_length=50,
                    ),
                ),
                ("credits_amount", models.PositiveIntegerField(default=0, help_text="Additional message credits provided")),
                ("agents_amount", models.PositiveIntegerField(default=0, help_text="Additional agents provided")),
                ("storage_mb_amount", models.PositiveIntegerField(default=0, help_text="Additional storage in MB")),
                ("stripe_price_id", models.CharField(blank=True, max_length=255, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Plan Addon",
                "verbose_name_plural": "Plan Addons",
                "db_table": "plan_addons",
                "ordering": ["sort_order", "price_monthly"],
            },
        ),
    ]
