# Generated by Django 4.2.7 on 2025-10-03 19:40

import apps.core.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WebhookEvent",
            fields=[
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "deleted_at",
                    models.DateTimeField(blank=True, db_index=True, null=True),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("stripe", "Stripe"),
                            ("crm", "CRM"),
                            ("user", "User Webhook"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "event_id",
                    models.CharField(help_text="External event ID", max_length=255),
                ),
                (
                    "event_type",
                    models.CharField(help_text="Type of webhook event", max_length=100),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "payload",
                    apps.core.models.JSONField(
                        default=dict, help_text="Raw webhook payload"
                    ),
                ),
                (
                    "headers",
                    apps.core.models.JSONField(
                        default=dict, help_text="Request headers"
                    ),
                ),
                (
                    "result",
                    apps.core.models.JSONField(
                        default=dict, help_text="Processing results"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error details if processing failed",
                        null=True,
                    ),
                ),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Webhook Event",
                "verbose_name_plural": "Webhook Events",
                "db_table": "webhook_events",
                "indexes": [
                    models.Index(
                        fields=["source", "event_type"],
                        name="webhook_eve_source_683499_idx",
                    ),
                    models.Index(
                        fields=["event_id"], name="webhook_eve_event_i_bb7559_idx"
                    ),
                    models.Index(
                        fields=["status"], name="webhook_eve_status_330e1f_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="webhook_eve_created_8fa52f_idx"
                    ),
                ],
            },
        ),
    ]
